apiVersion: v1
kind: Pod
metadata:
  annotations:
    tier: webserver
  name: nginx-server-dev
  labels:
    env: dev
    tier: frontend
spec:
  containers:
    - name: nginx-server-dev-container
      image: nginx:latest